name: Setup ecresolve
description:
inputs:
  version:
    description: "The version to install ecresolve"
    default: latest
    required: false
  github-token:
    description: "The token used when calling GitHub API"
    required: false
    default: ${{ github.token }}
runs:
  using: "composite"
  steps:
    - shell: bash
      env:
        github_token: ${{ inputs.github-token }}
        VERSION: ${{ inputs.version }}
      run: |
        set -eo pipefail
        ARCH=$(uname -m)
        if [ "${ARCH}" = "x86_64" ]; then
          GOARCH="amd64"
        elif [ "${ARCH}" = "aarch64" ]; then
          GOARCH="arm64"
        else
          echo "Unsupported architecture: ${ARCH}"
          exit 1
        fi

        echo "VERSION=${VERSION} GOARCH=${GOARCH}"

        api_request_args=("-sS")
        if [[ -n "$github_token" ]]; then
          api_request_args=("${api_request_args[@]}" -H "authorization: token $github_token")
        fi
        if [ "${VERSION}" = "latest" ]; then
          DOWNLOAD_URL=$(curl "${api_request_args[@]}" https://api.github.com/repos/ebi-yade/ecresolve/releases \
            | jq --arg matcher "linux.${GOARCH}." -r '[.[]|select(.prerelease==false)][0].assets[].browser_download_url|select(match($matcher))')
        else
          DOWNLOAD_URL=https://github.com/ebi-yade/ecresolve/releases/download/${VERSION}/ecresolve_${VERSION:1}_linux_${GOARCH}.tar.gz
        fi
        echo "DOWNLOAD_URL=${DOWNLOAD_URL}"
        mkdir -p ${RUNNER_TOOL_CACHE}/ecresolve
        cd /tmp
        curl -sfLO ${DOWNLOAD_URL}
        if [[ "${DOWNLOAD_URL}" =~ \.tar\.gz$ ]]; then
          FILENAME=$(basename $DOWNLOAD_URL .tar.gz)
          tar xzvf ${FILENAME}.tar.gz
          sudo install ecresolve ${RUNNER_TOOL_CACHE}/ecresolve/ecresolve
        elif [[ "${DOWNLOAD_URL}" =~ \.zip$ ]]; then
          FILENAME=$(basename $DOWNLOAD_URL .zip)
          unzip ${FILENAME}.zip
          sudo install ${FILENAME} ${RUNNER_TOOL_CACHE}/ecresolve/ecresolve
        fi

        echo "Adding ${RUNNER_TOOL_CACHE}/ecresolve to path..."
        echo "${RUNNER_TOOL_CACHE}/ecresolve" >> $GITHUB_PATH
        "${RUNNER_TOOL_CACHE}/ecresolve/ecresolve" --help # modify this line after --version is implemented in alecthomas/kong
